import {
  Archive, CalendarDays, ChevronLeft, ChevronRight, ClipboardList, MoreHorizontal,
  Pencil, Plus, RotateCcw, Search, ShoppingCart, UtensilsCrossed, X,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import {
  mealsApi, type MacroTotals, type Meal, type MealIngredientInput, type MealSlot,
  type PlannedInstance, type QuantityUnit, type ShoppingEntry, type WeeklyPlan,
} from "./api";
import ProductsPage, { type ProductCatalogFilters } from "./products/ProductsPage";
import { categoryLabels, productApi, type Product } from "./products/api";
import "./meals.css";

type Section = "products" | "meals" | "planner" | "shopping";
type DraftIngredient = { productId: string; productName: string; quantity: string; unit: QuantityUnit };
type PlannerTarget = { weekday: number; slot: MealSlot };

const slots: Array<{ id: MealSlot; label: string }> = [
  { id: "breakfast", label: "Desayuno" }, { id: "lunch", label: "Comida" }, { id: "snack", label: "Merienda" }, { id: "dinner", label: "Cena" }, { id: "extra", label: "Extra" },
];
const weekdays = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"];
const emptyMacros: MacroTotals = { proteinGrams: 0, carbohydrateGrams: 0, fatGrams: 0, kilocalories: 0 };

function errorMessage(error: unknown) { return typeof error === "string" ? error : "No se ha podido completar la operación."; }
function toIsoDate(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dateFromIso(value: string) { const [year, month, day] = value.split("-").map(Number); return new Date(year, month - 1, day, 12); }
function madridDate() {
  const values = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts();
  const part = (type: string) => values.find((value) => value.type === type)?.value ?? "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}
function currentWeekStart() { const today = dateFromIso(madridDate()); today.setDate(today.getDate() - ((today.getDay() + 6) % 7)); return toIsoDate(today); }
function offsetWeek(weekStart: string, offset: number) { const date = dateFromIso(weekStart); date.setDate(date.getDate() + offset * 7); return toIsoDate(date); }
function dayFor(weekStart: string, weekday: number) { const date = dateFromIso(weekStart); date.setDate(date.getDate() + weekday); return date; }
function dayIso(weekStart: string, weekday: number) { return toIsoDate(dayFor(weekStart, weekday)); }
function formatDay(weekStart: string, weekday: number) { return new Intl.DateTimeFormat("es-ES", { day: "numeric", month: "short" }).format(dayFor(weekStart, weekday)); }
function formatWeek(weekStart: string) { const format = new Intl.DateTimeFormat("es-ES", { day: "numeric", month: "short" }); return `${format.format(dayFor(weekStart, 0))} – ${format.format(dayFor(weekStart, 6))}`; }
function formatNumber(value: number, maximumFractionDigits = 0) { return new Intl.NumberFormat("es-ES", { maximumFractionDigits }).format(value); }
function gramsPerUnit(product: Product) {
  const presentation = product.presentation;
  if (!presentation) return undefined;
  if (presentation.kind === "package" && presentation.unitsPerPackage) return presentation.totalGrams / presentation.unitsPerPackage;
  return presentation.kind === "bulkByUnit" ? presentation.gramsPerUnit : undefined;
}
function slotLabel(slot: MealSlot) { return slots.find((item) => item.id === slot)?.label ?? slot; }

function useMadridToday() {
  const [today, setToday] = useState(madridDate);
  useEffect(() => {
    let timeout: number;
    const schedule = () => { timeout = window.setTimeout(() => { setToday(madridDate()); schedule(); }, 60_000 - (Date.now() % 60_000) + 50); };
    schedule(); return () => window.clearTimeout(timeout);
  }, []);
  return today;
}

function MacroTable({ macros, compact = false }: { macros: MacroTotals; compact?: boolean }) {
  return <dl className={compact ? "macro-table compact" : "macro-table"}><div><dt>Kcal</dt><dd>{formatNumber(macros.kilocalories)}</dd></div><div><dt>Proteínas</dt><dd>{formatNumber(macros.proteinGrams)} g</dd></div><div><dt>Carbos</dt><dd>{formatNumber(macros.carbohydrateGrams)} g</dd></div><div><dt>Grasas</dt><dd>{formatNumber(macros.fatGrams)} g</dd></div></dl>;
}

function IngredientRows({ drafts, products, onChange, onRemove }: { drafts: DraftIngredient[]; products: Product[]; onChange: (index: number, next: DraftIngredient) => void; onRemove: (index: number) => void }) {
  return <div className="ingredient-rows">{drafts.map((draft, index) => {
    const product = products.find((item) => item.id === draft.productId); const supportsUnits = Boolean(product && gramsPerUnit(product) !== undefined);
    return <div className="ingredient-row" key={`${index}-${draft.productId}`}>
      <input aria-label={`Producto ${index + 1}`} list={`ingredient-products-${index}`} onChange={(event) => { const match = products.find((item) => item.name.toLocaleLowerCase("es") === event.target.value.toLocaleLowerCase("es")); onChange(index, { ...draft, productId: match?.id ?? "", productName: event.target.value, unit: "grams" }); }} placeholder="Busca un producto" value={draft.productName} />
      <datalist id={`ingredient-products-${index}`}>{products.map((item) => <option key={item.id} value={item.name}>{item.status === "archived" ? "Archivado" : ""}</option>)}</datalist>
      <input aria-label={`Cantidad ${index + 1}`} inputMode="decimal" min="0.01" onChange={(event) => onChange(index, { ...draft, quantity: event.target.value })} step="0.01" type="number" value={draft.quantity} />
      {supportsUnits ? <select aria-label={`Unidad ${index + 1}`} onChange={(event) => onChange(index, { ...draft, unit: event.target.value as QuantityUnit })} value={draft.unit}><option value="grams">g</option><option value="units">uds</option></select> : <span className="fixed-unit">g</span>}
      <button aria-label="Retirar ingrediente" className="subtle-icon-button" disabled={drafts.length === 1} onClick={() => onRemove(index)} type="button"><X size={15} /></button>
    </div>;
  })}</div>;
}

function MealForm({ meal, products, onCancel, onSaved }: { meal?: Meal; products: Product[]; onCancel: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(meal?.name ?? "");
  const [drafts, setDrafts] = useState<DraftIngredient[]>(() => meal ? meal.ingredients.map((ingredient) => ({ productId: ingredient.productId, productName: ingredient.productName, quantity: String(ingredient.quantity), unit: ingredient.unit })) : [{ productId: "", productName: "", quantity: "", unit: "grams" }]);
  const [recommendedSlots, setRecommendedSlots] = useState<MealSlot[]>(meal?.recommendedSlots ?? []); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const updateDraft = (index: number, next: DraftIngredient) => setDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? next : item));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!drafts.length || drafts.some((draft) => !draft.productId || Number(draft.quantity) <= 0)) { setError("Añade al menos un ingrediente con un producto y una cantidad mayor que cero."); return; } setSaving(true); setError(null); try { const input = { name, ingredients: drafts.map<MealIngredientInput>((draft) => ({ productId: draft.productId, quantity: Number(draft.quantity), unit: draft.unit })), recommendedSlots }; if (meal) await mealsApi.updateMeal(meal.id, input); else await mealsApi.createMeal(input); await onSaved(); } catch (reason) { setError(errorMessage(reason)); } finally { setSaving(false); } }
  return <form className="meal-editor" onSubmit={submit}><div className="meal-editor-heading"><div><p className="section-kicker">{meal ? "EDITAR COMIDA" : "NUEVA COMIDA"}</p><h2>{meal?.name ?? "Crea una comida"}</h2></div><button aria-label="Cerrar formulario" className="product-icon-button" onClick={onCancel} type="button"><X size={17} /></button></div>
    {!products.length ? <p className="inline-note">Necesitas crear primero un producto activo.</p> : <><label className="meal-field"><span>Nombre</span><input autoFocus onChange={(event) => setName(event.target.value)} required value={name} /></label><fieldset className="meal-fieldset"><legend>Ingredientes</legend><p>Empieza escribiendo el producto. Las unidades solo se ofrecen cuando existe una conversión válida.</p><IngredientRows drafts={drafts} onChange={updateDraft} onRemove={(index) => setDrafts((current) => current.filter((_, itemIndex) => itemIndex !== index))} products={products} /><button className="text-action" onClick={() => setDrafts((current) => [...current, { productId: "", productName: "", quantity: "", unit: "grams" }])} type="button"><Plus size={15} /> Añadir producto</button></fieldset><fieldset className="meal-fieldset"><legend>Momentos recomendados <small>opcionales</small></legend><div className="slot-checks">{slots.map((slot) => <label key={slot.id}><input checked={recommendedSlots.includes(slot.id)} onChange={() => setRecommendedSlots((current) => current.includes(slot.id) ? current.filter((item) => item !== slot.id) : [...current, slot.id])} type="checkbox" />{slot.label}</label>)}</div></fieldset></>}
    {error && <p className="form-error" role="alert">{error}</p>}<div className="editor-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={saving || !products.length} type="submit">{saving ? "Guardando…" : meal ? "Guardar cambios" : "Crear comida"}</button></div>
  </form>;
}

function MealsPage({ search, onSearchChange, productFilter, onClearProductFilter }: { search: string; onSearchChange: (value: string) => void; productFilter?: Product; onClearProductFilter: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [allProducts, setAllProducts] = useState<Product[]>([]); const [meals, setMeals] = useState<Meal[]>([]); const [status, setStatus] = useState<"active" | "archived">("active"); const [editing, setEditing] = useState<Meal | null | undefined>(undefined); const [actionsFor, setActionsFor] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function refresh() { setLoading(true); setError(null); try { const [nextMeals, activeProducts, archivedProducts] = await Promise.all([mealsApi.listMeals(status, search, productFilter?.id), productApi.list("active"), productApi.list("archived")]); setMeals(nextMeals); setProducts(activeProducts); setAllProducts([...activeProducts, ...archivedProducts]); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [status, search, productFilter?.id]);
  async function changeStatus(meal: Meal) { try { if (meal.status === "active") await mealsApi.archiveMeal(meal.id); else await mealsApi.restoreMeal(meal.id); await refresh(); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="workspace-section"><div className="section-toolbar"><div className="catalog-search"><Search size={17} /><input aria-label="Buscar comidas" onChange={(event) => onSearchChange(event.target.value)} placeholder="Buscar comidas" value={search} /></div><div className="toolbar-actions"><button className="archive-link" onClick={() => setStatus((current) => current === "active" ? "archived" : "active")} type="button"><Archive size={15} /> {status === "active" ? "Archivo" : "Volver a recetas"}</button><button className="primary-button" onClick={() => setEditing(null)} type="button"><Plus size={16} /> Añadir comida</button></div></div>
    {productFilter && <div className="active-filter">Contiene: <strong>{productFilter.name}</strong><button onClick={onClearProductFilter} type="button"><X size={14} /> Quitar filtro</button></div>}
    {editing !== undefined && <MealForm meal={editing ?? undefined} onCancel={() => setEditing(undefined)} onSaved={async () => { await refresh(); setEditing(undefined); }} products={editing ? allProducts : products} />}
    <div className="section-heading"><div><p className="section-kicker">{status === "active" ? "RECETAS" : "ARCHIVO"}</p><h2>{status === "active" ? "Tus comidas" : "Comidas archivadas"}</h2></div></div>{error && <p className="form-error" role="alert">{error}</p>}{loading && <p className="workspace-empty">Cargando comidas…</p>}{!loading && !error && !meals.length && <p className="workspace-empty">No hay comidas que coincidan con esta búsqueda.</p>}
    {!loading && !error && meals.length > 0 && <div className="meal-card-grid">{meals.map((meal) => <article className="meal-card" key={meal.id}><div className="meal-card-heading"><div><h3>{meal.name}</h3><p>{meal.ingredients.length} ingrediente{meal.ingredients.length === 1 ? "" : "s"}{meal.recommendedSlots.length ? ` · ${meal.recommendedSlots.map(slotLabel).join(", ")}` : ""}</p></div><div className="card-icon-actions"><button aria-label={`Editar ${meal.name}`} className="product-icon-button" onClick={() => setEditing(meal)} type="button"><Pencil size={16} /></button><button aria-label={`Más acciones de ${meal.name}`} className="product-icon-button" onClick={() => setActionsFor((current) => current === meal.id ? null : meal.id)} type="button"><MoreHorizontal size={17} /></button>{actionsFor === meal.id && <div className="card-menu"><button onClick={() => { setActionsFor(null); void changeStatus(meal); }} type="button">{meal.status === "active" ? "Archivar" : "Restaurar"}</button></div>}</div></div><ul>{meal.ingredients.map((ingredient, index) => <li key={`${meal.id}-${index}`}>{ingredient.productName}<span>{formatNumber(ingredient.quantity, 1)} {ingredient.unit === "grams" ? "g" : "uds"}</span></li>)}</ul><MacroTable compact macros={meal.macros} /></article>)}</div>}
  </section>;
}

function PlanInstanceEditor({ instance, products, onCancel, onSaved }: { instance: PlannedInstance; products: Product[]; onCancel: () => void; onSaved: () => Promise<void> }) {
  const [drafts, setDrafts] = useState<DraftIngredient[]>(instance.ingredients.map((ingredient) => ({ productId: ingredient.productId, productName: ingredient.productName, quantity: String(ingredient.quantity), unit: ingredient.unit }))); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!drafts.length || drafts.some((draft) => !draft.productId || Number(draft.quantity) <= 0)) { setError("La instancia debe tener al menos un ingrediente válido."); return; } setSaving(true); setError(null); try { await mealsApi.updatePlannedInstance(instance.id, drafts.map((draft) => ({ productId: draft.productId, quantity: Number(draft.quantity), unit: draft.unit }))); await onSaved(); } catch (reason) { setError(errorMessage(reason)); } finally { setSaving(false); } }
  return <form className="plan-editor" onSubmit={submit}><div className="meal-editor-heading"><div><p className="section-kicker">EDITAR INSTANCIA</p><h2>Comida planificada</h2></div><button aria-label="Cerrar edición" className="product-icon-button" onClick={onCancel} type="button"><X size={17} /></button></div><IngredientRows drafts={drafts} onChange={(index, next) => setDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? next : item))} onRemove={(index) => setDrafts((current) => current.filter((_, itemIndex) => itemIndex !== index))} products={products} /><button className="text-action" onClick={() => setDrafts((current) => [...current, { productId: "", productName: "", quantity: "", unit: "grams" }])} type="button"><Plus size={15} /> Añadir producto</button>{error && <p className="form-error" role="alert">{error}</p>}<div className="editor-actions"><button className="secondary-button" onClick={onCancel} type="button">Cancelar</button><button className="primary-button" disabled={saving} type="submit">{saving ? "Guardando…" : "Guardar instancia"}</button></div></form>;
}

function PlannerPage({ weekStart, onWeekChange }: { weekStart: string; onWeekChange: (weekStart: string) => void }) {
  const [plan, setPlan] = useState<WeeklyPlan | null>(null); const [meals, setMeals] = useState<Meal[]>([]); const [products, setProducts] = useState<Product[]>([]); const [target, setTarget] = useState<PlannerTarget | null>(null); const [editing, setEditing] = useState<PlannedInstance | null>(null); const [pickerQuery, setPickerQuery] = useState(""); const [draggedId, setDraggedId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const today = useMadridToday();
  async function refresh() { setError(null); try { const [nextPlan, activeMeals, archivedMeals, activeProducts, archivedProducts] = await Promise.all([mealsApi.listWeek(weekStart), mealsApi.listMeals("active"), mealsApi.listMeals("archived"), productApi.list("active"), productApi.list("archived")]); setPlan(nextPlan); setMeals([...activeMeals, ...archivedMeals]); setProducts([...activeProducts, ...archivedProducts]); } catch (reason) { setError(errorMessage(reason)); } }
  useEffect(() => { void refresh(); }, [weekStart]);
  async function addMeal(meal: Meal) { if (!target) return; try { await mealsApi.createPlannedInstance({ weekStart, weekday: target.weekday, slot: target.slot, mealId: meal.id }); setTarget(null); setPickerQuery(""); await refresh(); } catch (reason) { setError(errorMessage(reason)); } }
  async function remove(instance: PlannedInstance) { try { await mealsApi.removePlannedInstance(instance.id); await refresh(); } catch (reason) { setError(errorMessage(reason)); } }
  async function move(id: string, weekday: number, slot: MealSlot, position: number) { try { await mealsApi.movePlannedInstance(id, { weekday, slot, position }); await refresh(); } catch (reason) { setError(errorMessage(reason)); } finally { setDraggedId(null); } }
  const mealName = (instance: PlannedInstance) => meals.find((meal) => meal.id === instance.sourceMealId)?.name ?? "Comida planificada";
  const pickerMeals = useMemo(() => { if (!target) return []; const normalized = pickerQuery.trim().toLocaleLowerCase("es"); return meals.filter((meal) => meal.status === "active" && meal.name.toLocaleLowerCase("es").includes(normalized)).sort((left, right) => Number(right.recommendedSlots.includes(target.slot)) - Number(left.recommendedSlots.includes(target.slot)) || left.name.localeCompare(right.name, "es")); }, [meals, pickerQuery, target]);
  return <section className="planner-section"><div className="planner-toolbar"><div className="week-navigation"><button aria-label="Semana anterior" className="product-icon-button" onClick={() => onWeekChange(offsetWeek(weekStart, -1))} type="button"><ChevronLeft size={18} /></button><div><p className="section-kicker">SEMANA</p><h2>{formatWeek(weekStart)}</h2></div><button aria-label="Semana siguiente" className="product-icon-button" onClick={() => onWeekChange(offsetWeek(weekStart, 1))} type="button"><ChevronRight size={18} /></button><button className="today-button" onClick={() => onWeekChange(currentWeekStart())} type="button">Hoy</button></div></div>{error && <p className="form-error" role="alert">{error}</p>}
    <div className="real-planner-card"><div className="real-week-grid"><div className="real-grid-corner"><CalendarDays size={15} /></div>{weekdays.map((label, weekday) => { const dayMacros = plan?.dailyMacros.find((item) => item.weekday === weekday)?.macros ?? emptyMacros; const isToday = dayIso(weekStart, weekday) === today; return <div className={isToday ? "real-day-heading today" : "real-day-heading"} key={label}><span>{label}</span><strong>{formatDay(weekStart, weekday)}</strong><small>{formatNumber(dayMacros.kilocalories)} kcal</small></div>; })}{slots.flatMap((slot) => [<div className="real-slot-heading" key={`${slot.id}-heading`}><span>{slot.label}</span></div>, ...weekdays.map((_, weekday) => { const instances = (plan?.instances ?? []).filter((instance) => instance.slot === slot.id && instance.weekday === weekday).sort((left, right) => left.position - right.position); const isToday = dayIso(weekStart, weekday) === today; const macros = plan?.dailyMacros.find((item) => item.weekday === weekday)?.macros ?? emptyMacros; return <div className={isToday ? "real-slot-cell today" : "real-slot-cell"} key={`${slot.id}-${weekday}`} onDragOver={(event) => event.preventDefault()} onDrop={() => draggedId && void move(draggedId, weekday, slot.id, instances.length)}>{instances.map((instance, index) => <div className={instance.isModified ? "planned-chip modified" : "planned-chip"} draggable key={instance.id} onDragOver={(event) => event.preventDefault()} onDragStart={() => setDraggedId(instance.id)} onDrop={(event) => { event.stopPropagation(); if (draggedId) void move(draggedId, weekday, slot.id, index); }}><button onClick={() => setEditing(instance)} type="button"><strong>{mealName(instance)}</strong><span>{formatNumber(instance.macros.kilocalories)} kcal{instance.isModified && " · modificada"}</span></button><button aria-label="Quitar" className="remove-planned" onClick={() => void remove(instance)} type="button">×</button></div>)}{slot.id === "extra" && <div className="day-macro-summary"><MacroTable compact macros={macros} /></div>}<button aria-label={`Añadir en ${slot.label}`} className="add-plan-button" onClick={() => setTarget({ weekday, slot: slot.id })} type="button"><Plus size={14} /></button></div>; })])}</div></div>
    {target && <div className="workspace-modal"><div className="picker-card"><div className="meal-editor-heading"><div><p className="section-kicker">AÑADIR AL PLAN</p><h2>{slotLabel(target.slot)} · {weekdays[target.weekday]}</h2></div><button aria-label="Cerrar selector" className="product-icon-button" onClick={() => setTarget(null)} type="button"><X size={17} /></button></div><div className="catalog-search"><Search size={17} /><input autoFocus onChange={(event) => setPickerQuery(event.target.value)} placeholder="Buscar comida" value={pickerQuery} /></div>{!pickerMeals.length ? <p className="inline-note">No hay comidas activas que coincidan.</p> : <div className="meal-choice-list">{pickerMeals.map((meal) => <button key={meal.id} onClick={() => void addMeal(meal)} type="button"><span><strong>{meal.name}</strong><MacroTable compact macros={meal.macros} /></span><Plus size={17} /></button>)}</div>}</div></div>}
    {editing && <div className="workspace-modal"><PlanInstanceEditor instance={editing} onCancel={() => setEditing(null)} onSaved={async () => { await refresh(); setEditing(null); }} products={products} /></div>}
  </section>;
}

function recommendationLabel(entry: ShoppingEntry) { const recommendation = entry.recommendation; if (!recommendation) return `${formatNumber(entry.pendingGrams)} g`; if (recommendation.kind === "packages") return `${recommendation.packages} paquete${recommendation.packages === 1 ? "" : "s"}`; if (recommendation.kind === "units") return `${recommendation.units} ud${recommendation.units === 1 ? "" : "s"}`; return `${formatNumber(recommendation.grams)} g`; }

function ShoppingPage({ weekStart }: { weekStart: string }) {
  const [entries, setEntries] = useState<ShoppingEntry[]>([]); const [amounts, setAmounts] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function refresh() { setLoading(true); setError(null); try { setEntries(await mealsApi.listShoppingList(weekStart)); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [weekStart]);
  async function saveAvailable(entry: ShoppingEntry) { const grams = Number(amounts[entry.product.id] ?? entry.availableGrams); if (!Number.isFinite(grams) || grams < 0) { setError("«Tienes» debe ser una cantidad en gramos igual o mayor que cero."); return; } try { await mealsApi.setWeeklyAvailable(weekStart, entry.product.id, grams); await refresh(); } catch (reason) { setError(errorMessage(reason)); } }
  return <section className="shopping-section"><div className="section-heading"><div><p className="section-kicker">COMPRA SEMANAL</p><h2>{formatWeek(weekStart)}</h2><p className="shopping-intro">Indica lo que ya tienes para esta semana y la recomendación se recalculará.</p></div></div>{error && <p className="form-error" role="alert">{error}</p>}{loading && <p className="workspace-empty">Calculando la compra…</p>}{!loading && !error && !entries.length && <p className="workspace-empty">Esta semana todavía no tiene comidas planificadas.</p>}{!loading && !error && entries.length > 0 && <div className="shopping-entry-list">{entries.map((entry) => <article className={entry.pendingGrams === 0 ? "shopping-entry complete" : "shopping-entry"} key={entry.product.id}><div><span className="product-category">{categoryLabels[entry.product.category]}</span><h3>{entry.product.name}</h3><p>Necesitas <strong>{formatNumber(entry.neededGrams)} g</strong> · Pendiente <strong>{formatNumber(entry.pendingGrams)} g</strong></p>{entry.theoreticalLeftoverGrams !== undefined && <small>Sobrante teórico: {formatNumber(entry.theoreticalLeftoverGrams)} g</small>}</div><div className="shopping-recommendation"><span>Compra recomendada</span><strong>{recommendationLabel(entry)}</strong>{entry.estimatedCostCents !== undefined && <small>{(entry.estimatedCostCents / 100).toLocaleString("es-ES", { style: "currency", currency: "EUR" })}</small>}</div><label className="shopping-available"><span>Tienes · g</span><input aria-label={`Tienes de ${entry.product.name} en gramos`} inputMode="decimal" min="0" onBlur={() => void saveAvailable(entry)} onChange={(event) => setAmounts((current) => ({ ...current, [entry.product.id]: event.target.value }))} step="1" type="number" value={amounts[entry.product.id] ?? String(entry.availableGrams)} /></label></article>)}</div>}</section>;
}

export default function MealsWorkspace() {
  const [section, setSection] = useState<Section>("planner"); const [weekStart, setWeekStart] = useState(currentWeekStart); const [productFilters, setProductFilters] = useState<ProductCatalogFilters>({ query: "", category: "all" }); const [mealSearch, setMealSearch] = useState(""); const [mealProductFilter, setMealProductFilter] = useState<Product | undefined>();
  const tabs: Array<{ id: Section; label: string; icon: typeof UtensilsCrossed }> = [{ id: "planner", label: "Planificador", icon: CalendarDays }, { id: "shopping", label: "Compra", icon: ShoppingCart }, { id: "products", label: "Productos", icon: ClipboardList }, { id: "meals", label: "Comidas", icon: UtensilsCrossed }];
  return <section className="meals-workspace"><nav aria-label="Secciones de comidas" className="workspace-tabs">{tabs.map(({ id, label, icon: Icon }) => <button className={section === id ? "workspace-tab active" : "workspace-tab"} key={id} onClick={() => setSection(id)} type="button"><Icon size={16} /> {label}</button>)}</nav>{section === "products" && <ProductsPage filters={productFilters} onFiltersChange={setProductFilters} onSearchMeals={(product) => { setMealProductFilter(product); setSection("meals"); }} />}{section === "meals" && <MealsPage onClearProductFilter={() => setMealProductFilter(undefined)} onSearchChange={setMealSearch} productFilter={mealProductFilter} search={mealSearch} />}{section === "planner" && <PlannerPage onWeekChange={setWeekStart} weekStart={weekStart} />}{section === "shopping" && <ShoppingPage weekStart={weekStart} />}</section>;
}
